config/routes.rb
Rails.application.routes.draw do
  get 'dishes/create'
  get 'dishes/new'
  get 'welcome/index'
  root 'welcome#index'
  get 'meal_plans/new'
  post 'meal_plans/create'
  get 'meal_plans/edit'
  get 'sessions/new'
  root 'static_pages#home'
  get 'meal_plans/new/update_dish_list', to: 'meal_plans#update_dish_list', as: 'update_dish_list'
  get 'meal_plans/new/custom_dish', to: 'meal_plans#custom_dish', as: 'custom_dish' 
  post 'meal_plans/new/refresh_dish_list', to: 'meal_plans#refresh_dish_list', as: 'refresh_dish_list'
  get '/home', to: 'static_pages#home'
  get '/about', to: 'static_pages#about'
  get '/signup', to: 'users#new', as: 'new_user'
  post '/signup', to: 'users#create'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :users
  resources :meal_plans
  resources :dishes

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dish.rb
class Dish < ApplicationRecord

  has_many :meal_plans

end

app/models/meal_plan.rb
class MealPlan < ApplicationRecord
  belongs_to :user
  has_one :restriction
  has_many :dishes

  validates :name, presence: true
  validates :date, presence: true

  serialize :list_of_dishes

  accepts_nested_attributes_for :dishes

end

app/models/restriction.rb
class Restriction < ApplicationRecord
  belongs_to :meal_plan
end

app/models/user.rb
class User < ApplicationRecord
  validates :username, presence: true, 
                       length: { maximum: 50 }, 
                       uniqueness: true

  has_many :meal_plans
  serialize :meal_plans
end

app/models/weekly_menu.rb
class WeeklyMenu < ApplicationRecord
  has_many :dishes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def new
  end
end

app/controllers/dishes_controller.rb
class DishesController < ApplicationController
  def create
  	@dish = Dish.new(dish_params)
    if @dish.save
      #log_in(@user)
      flash[:success] = "Welcome to Custom Meal Maker"
      redirect_to meal_plans_new_path
    else
      flash.now[:danger] = "Error creating account"
      #render 'new'
    end
  end

  def new
  	@dish = Dish.new
    #@available_dishes = nil # will be by weekly once week is implemented
    #@chosen_dishes = nil
  end

private

	def dish_params
      params.require(:dish).permit(:created_at, :updated_at, :name, :calories, :total_fat, :cholesterol, :sodium, :carbs, :suger, :protein, :location, :course)
    end

end


=begin

<%= f.hidden_field :user_id, :value => current_user.id %>

    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.string "name"
    t.integer "calories"
    t.integer "total_fat"
    t.integer "cholesterol"
    t.integer "sodium"
    t.integer "carbs"
    t.integer "suger"
    t.integer "protein"
    t.string "location"
    t.string "course"

=end

app/controllers/meal_plans_controller.rb
class MealPlansController < ApplicationController

  def new
    @meal_plan = MealPlan.new
    @user = current_user
    @available_dishes = nil # will be by weekly once week is implemented
    @chosen_dishes = nil
  end

  def create
    logger.debug("Hitting MealPlans#create")
    @meal_plan = MealPlan.new(meal_plan_params)
    logger.debug(@meal_plan.name)
    respond_to do |format|
      if @meal_plan.save
        format.html { redirect_to meal_plan_url(@meal_plan), notice: "Meal Plan successfully saved." }
      else
        logger.debug "Having trouble saving..."
        render "new"
      end
    end 
    logger.debug @meal_plan.errors.full_messages
  end

  def show
    @meal_plan = MealPlan.find(params[:id])
    @chosen_dishes = Dish.where(id: @meal_plan.list_of_dishes.split(','))
    @nutrition = {  'calories'    => @chosen_dishes.map{ |dish| dish.calories }.reduce(:+),
                    'fat'         => @chosen_dishes.map{ |dish| dish.total_fat }.reduce(:+),
                    'cholesterol' => @chosen_dishes.map{ |dish| dish.cholesterol }.reduce(:+), 
                    'sodium'      => @chosen_dishes.map{ |dish| dish.sodium }.reduce(:+),
                    'carbs'       => @chosen_dishes.map{ |dish| dish.carbs }.reduce(:+),
                    'suger'       => @chosen_dishes.map{ |dish| dish.suger }.reduce(:+),
                    'protein'     => @chosen_dishes.map{ |dish| dish.protein }.reduce(:+),  
                  }
  end

  def update_dish_list
    @chosen_dishes = Dish.where(id: params[:data_value])

    @nutrition =  { 'calories'    => @chosen_dishes.map{ |dish| dish.calories }.reduce(:+),
                    'fat'         => @chosen_dishes.map{ |dish| dish.total_fat }.reduce(:+),
                    'cholesterol' => @chosen_dishes.map{ |dish| dish.cholesterol }.reduce(:+), 
                    'sodium'      => @chosen_dishes.map{ |dish| dish.sodium }.reduce(:+),
                    'carbs'       => @chosen_dishes.map{ |dish| dish.carbs }.reduce(:+),
                    'suger'       => @chosen_dishes.map{ |dish| dish.suger }.reduce(:+),
                    'protein'     => @chosen_dishes.map{ |dish| dish.protein }.reduce(:+),
                  }


    logger.debug @nutrition

    respond_to do |format|
      format.js { flash[:success] = "Added Dishes"}
    end
  end

  def refresh_dish_list
    logger.debug "Hitting change_location"
    # Yo this is really ugly someone make this better
    if params[:location] && params[:course].blank?
      logger.debug "Location"
      @available_dishes = Dish.where(location: params[:location])
    elsif params[:course] && params[:location].blank?
      logger.debug "Course"
      @available_dishes = Dish.where(course: params[:course])
    elsif params[:location] && params[:course]
      logger.debug "Location and Course"
      @available_dishes = Dish.where(location: params[:location], course: params[:course])
    end


  end

  def edit
    logger.debug "Meal Plan #{params[:id]}"
    @meal_plan = MealPlan.find(params[:id])
  end

  private

    def meal_plan_params
      params.require(:meal_plan).permit(:id, :user_id, :list_of_dishes, :name, :course, :location, :date)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new

  end

  def create
    user = User.find_by(username: params[:session][:username])
    if user
      flash[:success] = "Successfully logged in"
      log_in user
      redirect_to user_path(user)
    else
      flash[:danger] = "Error Logging In"
      render 'new'
    end
  end

  def destroy
    session.delete(:user_id)
    @current_user = nil
    redirect_to root_url
  end

end

app/controllers/test_controller.rb
class TestController < ApplicationController
  def thing
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include SessionsHelper
  
  def create
    @user = User.new(user_params)
    if @user.save
      log_in(@user)
      flash[:success] = "Welcome to Manoa Meals"
      redirect_to user_path(@user)
    else
      flash.now[:danger] = "Error creating account"
      render 'new'
    end
  end

  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
    @meal_plans = MealPlan.where(user_id: @user.id)
    
  end

  private

    def user_params
      params.require(:user).permit(:username, :email_address, :first_name, :last_name)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/dishes_helper.rb
module DishesHelper
end

app/helpers/meal_plans_helper.rb
module MealPlansHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    if session[:user_id]
      @current_user ||= User.find_by(id: session[:user_id])
    end
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/test_helper.rb
module TestHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/dishes/_new_custom_dish.html.erb
<%= form_for(new_dish_path(@new_dish)) do |f| %>
<div class="modal-dialog modal-dialog-centered" role="document">
  <div class="modal-content">
    <div class="modal-header">
       <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
       <h3 id="myModalLabel">Custom Dish</h3>
     </div>
     <div class="modal-body">
      <%#= f.label :name %>
     </div>
     <div class="modal-footer">
       <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
       <%= f.submit %>
     </div>
    </div>
</div>
<% end %>

app/views/dishes/create.html.erb
<h1>Dishes#create</h1>
<p>Find me in app/views/dishes/create.html.erb</p>

app/views/dishes/new.html.erb
<div class='container'>
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <div class="panel panel-default">
        <h1>New Custom Dish</h1>

        <div class="panel-body">
          <%= form_for(@dish) do |f| %>
            <div class="row">
              <div class='col-md-6'>
                <div class="form-group">
                  <%= f.label :name %>
                  <%= f.text_field :name, class: 'form-control' %>
                </div>
              </div>
              <div class='col-md-6'>
                <div class="form-group">
                  <%= f.label :calories %>
                  <%= f.text_field :calories, class: 'form-control' %>
                </div>
              </div>
            </div>
            <div class='row'>
              <div class='col-md-4'>
                <div class='form-group'>
                  <%= f.label :carbs %>
                  <%= f.text_field :carbs, class: 'form-control' %>
                </div>
              </div>
              <div class='col-md-4'>
                <div class='form-group'>
                  <%= f.label :protein %>
                  <%= f.text_field :protein, class: 'form-control' %>
                </div>
              </div>
              <div class='col-md-4'>
                <div class='form-group'>
                  <%= f.label :total_fat %>
                  <%= f.text_field :total_fat, class: 'form-control' %>
                </div>
              </div>
            </div>
            <div class='show-more'>
              <div class='row'>
                <div class='col-md-4'>
                  <div class='form-group'>
                    <%= f.label :cholesterol %>
                    <%= f.text_field :cholesterol, class: 'form-control' %>
                  </div>
                </div>
                <div class='col-md-4'>
                  <div class='form-group'>
                    <%= f.label :sodium %>
                    <%= f.text_field :sodium, class: 'form-control' %>
                  </div>
                </div>
                <div class='col-md-4'>
                  <div class='form-group'>
                    <%= f.label :suger %>
                    <%= f.text_field :suger, class: 'form-control' %>
                  </div>
                </div>
              </div>
            </div>
            <a href="" id='show-more' style="text-align:center;">Show More</a>
            <div class="hidden_fields">
              <%= f.hidden_field :course, class: 'form-control', value: 'custom' %>

            </div>
            <%= f.submit "Create Dish", class: 'btn' %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>
<script>
  $(document).ready(function() {
    $(".show-more").hide();

    $("#show-more").on('click', function() {
      $('.show-more').show();
      $('#show-mode').hide();
      event.preventDefault();
    })
  })
</script>

<!-- <div class='panel-body'>
            <%#= form_for(@dish) do |f| %>
            
            <div class='form-group'>
                <%#= f.label :created_at %>
                <%#= f.hidden_field :created_at, class: 'form-control' %>
            </div>


            <%#= f.hidden_field :user_id, :value => current_user.id %>

            <div class='form-group'>
                <%#= f.label :updated_at %>
                <%#= f.hidden_field :updated_at, class: 'form-control' %>
            </div>

            <div class='form-group'>
                <%#= f.label :name %>
                <%#= f.text_field :name, class: 'form-control' %>
            </div>

            <div class='form-group'>
                <%#= f.label :calories %>
                <%#= f.text_field :calories, class: 'form-control' %>
            </div>

            <div class='form-group'>
                <%#= f.label :total_fat %>
                <%#= f.text_field :total_fat, class: 'form-control' %>
            </div>

            <div class='form-group'>
                <%#= f.label :cholesterol %>
                <%#= f.text_field :cholesterol, class: 'form-control' %>
            </div>

            <div class='form-group'>
                <%#= f.label :sodium %>
                <%#= f.text_field :sodium, class: 'form-control' %>
            </div>

            <div class='form-group'>
                <%#= f.label :carbs %>
                <%#= f.text_field :carbs, class: 'form-control' %>
            </div>
				
			<div class='form-group'>
                <%#= f.label :suger %>
                <%#= f.text_field :suger, class: 'form-control' %>
            </div>

            <div class='form-group'>
                <%#= f.label :protein %>
                <%#= f.text_field :protein, class: 'form-control' %>
            </div>

            <div class='form-group'>
                <%#= f.label :location %>
                <%#= f.hidden_field :location, class: 'form-control', :value => 'gateway' %>
            </div>

            <div class='form-group'>
                <%#= f.label :course %>
                <%#= f.text_field :course, class: 'form-control' %>
                <%#= select_tag(:course,
                      options_for_select( [ ['Breakfast', 'breakfast'], ['Lunch', 'lunch'], ['Dinner', 'dinner'] ] ), 
                     class: 'form-control', prompt: "Choose Course" ) %>
            </div>

            

              <%#= f.submit "Make my meal", class: "btn" %>
              <%#= f.submit "Make my meal", class: "btn" %>
              <%#= link_to 'Test', dishes_new_path, class:'btn pull-right' %>

            <%# end %>
          </div>
      </div> -->

app/views/dishes/new_custom_dish.js.erb
$("#modal-window").html("<%= escape_javascript(render 'dishes/new_custom_dish') %>");
$("#modal-window").modal();

app/views/meal_plans/_available_dishes.html.erb
<% if available_dishes.nil? %>
  <p>Please Select a Location</p>
<% else %>
    <table class="table table-hover">
      <thead>
        <tr>
          <th scope="col">Name</th>
          <th scope="col">Calories</th>
        </tr>
      </thead>
      <tbody>
        <% available_dishes.each do |dish| %>
          <tr class="table_row">
            <th scope="row" class="dish_name" id="<%= dish.id %>"><%= dish.name %></th>
            <td id="calories<%= dish.id %>"><%= dish.calories %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
<% end %>

app/views/meal_plans/_custom_dishes.html.erb
<h2> Test </h2>

app/views/meal_plans/_dish_list.html.erb
<% if chosen_dishes.nil? %>
  <p>Empty</p>
<% else %> 
<table class="table">
  <thead>
    <tr>
      <th scope="col">Name</th>
      <th scope="col">Calories</th>
      <th scope="col">Quantity</th>
      <th scope="col">Remove?</th>
    </tr>
  </thead>
  <tbody>
    <% chosen_dishes.each do |dish| %>
      <tr>
        <th scope="row" class="dish_name" id="<%= dish.id %>"><%= dish.name %></th>
        <td id="calories<%= dish.id %>"><%= dish.calories %></td>
        <td id="quantity">
          <select id="quantity_select">
            <option selected>1</option>
            <option>2</option>
            <option>3</option>  
          </select>
        </td>
        <td id="remove"><span class="glyphicon glyphicon-remove" aria-hidden="true"></span></td>
      </tr>
    <% end %>
  </tbody>
</table>
<% end %>

app/views/meal_plans/change_location.js.erb
$(".available_dishes").html("<%= escape_javascript(render partial: 'available_dishes', locals: { available_dishes: @available_dishes } ) %> ");

app/views/meal_plans/custom.html.erb
custom.html.erb

app/views/meal_plans/custom_dish.js.erb
$('#custom_id').html("<%= escape_javascript(render partial: 'custom_dishes') %>");

app/views/meal_plans/edit.html.erb
<div class="jumbotron">
  <h2>New Meal Plan</h2>
  <%= form_for(@meal_plan, url: meal_plans_create_path) do |f| %>

      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.hidden_field :user_id, :value => current_user.id %>

      <%= f.label :date %>
      <%= f.date_field :date %>

      <%= f.label :location %>
      <%= select_tag(:location, 
          options_for_select([['Gateway Cafe', 'gateway'], ['Hale Aloha Cafe','hale aloha']]),
          id: 'location_id', prompt: 'Choose Location') %>

      <%= f.label :course %>
      <%= select_tag(:course,
            options_for_select( [ ['Breakfast', 'breakfast'], ['Lunch', 'lunch'], ['Dinner', 'dinner'] ] ), 
            id: 'course_id', prompt: "Choose Course" ) %>

      <%= f.hidden_field :nutrition, class: 'nutrition_field' %>
      <%= @nutrition.inspect %>
</div>
<div class="row"> 
  <div class="col-md-6 jumbotron">
    <h2>Restrictions</h2>
    <p>Work in Progress</p>

  </div>
  <div class="col-md-6 jumbotron">
    <h2>Nutrition</h2>
    <div class="row">
      <%#= render partial: "nutrition", locals: { nutrition: @nutrition } %>
      <div class="col-md-2">
        <span id="nutr-calories" class="odometer">0</span><br>
        <span class="nutr-label">Calories</span>
      </div>
      <div class="col-md-2">
        <span id="nutr-fat" class="odometer">0</span><br>
        <span class="nutr-label">Fat</span>
      </div>
      <div class="col-md-2">
        <span id="nutr-carbs" class="odometer">0</span><br>
        <span class="nutr-label">Carbs</span>
      </div>
      <div class="col-md-2">
        <span id="nutr-cholesterol" class="odometer">0</span><br>
        <span class="nutr-label">Cholesterol</span>
      </div>
      <div class="col-md-2">
        <span id="nutr-sodium" class="odometer">0</span><br>
        <span class="nutr-label">Sodium</span>
      </div>
      <div class="col-md-2">
        <span id="nutr-sugar" class="odometer">0</span><br>
        <span class="nutr-label">Sugar</span>
      </div>
      <div class="col-md-2">
        <span id="nutr-protein" class="odometer">0</span><br>
        <span class="nutr-label">Protein</span>
      </div>
    </div>
  </div>
</div>
<div class="row"> <!-- User Meal Plan -->
  <div class="col-md-6 jumbotron">

      <div class="chosen-dishes">
        <h2>Chosen Dishes</h3>
        <div class="dishes">
          <%= render partial: "dish_list", locals: { chosen_dishes: @chosen_dishes } %>
        </div>
      </div>

      <%= f.hidden_field :list_of_dishes, id: 'list_of_dishes' %>

      <%= f.submit "Submit", class: "btn btn-primary" %>

    <% end %>
  </div>
  <div class="col-md-6 jumbotron">
    <div class="available_dishes">
      <%= render partial: 'available_dishes', locals: { available_dishes: @available_dishes } %>
    </div>
      <%= link_to 'Add to Meal Plan', '#', class: 'btn btn-primary', id: "add_dishes_btn" %>
      <%= link_to 'Add Custom Dish', custom_dish_path, :remote => true, class: 'btn btn-primary' %>
        <div id="custom_id">

      </div>
  </div>
</div>  


<script>
  var calories = 0;
  var fats = 0;
  var carbs = 0;
  var list_of_dishes = [];
  
  function refresh_dish_list() {
    $.ajax({
      url: '/meal_plans/new/refresh_dish_list',
      type: 'POST',
      dataType: 'script',
      data: {
        location: $('#location_id').val(),
        course: $('#course_id').val()
      }
    });
  }

  $(document).ready(function() {

    window.odometerOptions = {
      auto: false,
      format: '(,ddd)',
      duration: 500,
      theme: 'minimal',
      animation: 'count'
    }



    $(document).on('click', 'tr.table_row', function() {
      console.log("Hit")
      // On click, add ID to array, save into global variable. Add Button at bottom of available dishes to submit
      if (list_of_dishes.indexOf($(this).children(".dish_name").attr("id")) === -1 ) {
        list_of_dishes.push($(this).children(".dish_name").attr('id'));
      }
      $(this).addClass('success');
    });

    $('#add_dishes_btn').on('click', function() {
      $.ajax({
        url: '/meal_plans/new/update_dish_list',
        type: 'GET',
        dataType: 'script',
        data: {
          data_value: list_of_dishes
        }
      });
      $('#list_of_dishes').val(list_of_dishes);
      event.preventDefault();
      $('tr.table_row').removeClass('success');

    });

    $("#location_id").on('change', refresh_dish_list);
    $("#course_id").on('change', refresh_dish_list);

  });


</script>

app/views/meal_plans/new.html.erb
<%= @meal_plan.errors.full_messages.first if @meal_plan.errors.any? %>

<div class="container">
  <div class="panel panel-default">
    <div class="row">
      <div class="col-md-6">
        <div class="section-header">
          <div class="panel-header">
            <span class="section-header__title h2">New Meal Plan</span>
            <!-- <h2 class="section-header__title">New Meal Plan</h2> -->
          </div>
        </div>
        <div class="panel-body">
          <%= form_for(@meal_plan, url: meal_plans_create_path) do |f| %>
            <div class="row">
              <div class="col-md-6">
                <div class="form-group">
                  <%= f.label :name %>
                  <%= f.text_field :name, class: 'form-control' %></p>
                </div>
              </div>
              <%= f.hidden_field :user_id, :value => current_user.id %>
              <div class="col-md-6">
                <div class="form-group">
                  <%= f.label :date %>
                  <%= f.date_field :date, class: 'form-control' %>
                </div>
              </div>
            </div>
            <div class="row">
              <div class="col-md-6">
                <div class="form-group">
                  <%= f.label :location %>
                  <%= f.select(:location, options_for_select([['Gateway Cafe', 'gateway'], ['Hale Aloha Cafe','hale aloha']]), { prompt: 'Choose Location' }, { :class => 'form-control', :id => 'location_id'} ) %>
                </div>
              </div>
              <div class="col-md-6">
                <div class="form-group">
                 <%= f.label :course %>
                 <%= f.select(:course, options_for_select([ ['Breakfast', 'breakfast'], ['Lunch', 'lunch'], ['Dinner', 'dinner'], ['Custom', 'custom'] ]), {prompt: 'Choose Course'}, {class: 'form-control', id: 'course_id'}) %>
                </div>
                <%= f.hidden_field :nutrition, class: 'nutrition_field' %>
                <%= f.submit "Submit", class: "btn pull-right" %>
              </div>
            </div>
        </div>
      </div> <!-- col-md-6 -->
      <div class="col-md-6">
        <div class='section-header'>
          <span class="section-header__title h2">Restrictions</span>
        </div>
        <h2 class="text-center">Work in Progress<h2>
      </div>
    </div> <!-- row -->
  </div> <!-- panel panel-default -->
  <div class="panel panel-default nutrition">
    <div class="row">
      <div class="section-header">
        <span class="section-header__title h2">Nutrition</span>
      </div>
      <div class="col-md-2 nutrition-values">
        <span id="nutr-calories" class="odometer">0</span><br>
        <span class="nutr-label">Calories</span>
      </div>
      <div class="col-md-2 nutrition-values">
        <span id="nutr-fat" class="odometer">0</span><br>
        <span class="nutr-label">Fat</span>
      </div>
      <div class="col-md-2 nutrition-values">
        <span id="nutr-carbs" class="odometer">0</span><br>
        <span class="nutr-label">Carbs</span>
      </div>
      <div class="col-md-2 nutrition-values">
        <span id="nutr-sodium" class="odometer">0</span><br>
        <span class="nutr-label">Sodium</span>
      </div>

      <div class="col-md-2 nutrition-values">
        <span id="nutr-sugar" class="odometer">0</span><br>
        <span class="nutr-label">Sugar</span>
      </div>
      <div class="col-md-2 nutrition-values">
        <span id="nutr-protein" class="odometer">0</span><br>
        <span class="nutr-label">Protein</span>
      </div>
    </div>
  </div>
  <div class="panel panel-default bottom-panel">
    <div class='row'>
      <div class="col-md-6">
        <div class='section-header'>
          <span class='section-header__title h2'>Chosen Dishes</span>
        </div>
        <div class="dishes">
          <%= render partial: "dish_list", locals: { chosen_dishes: @chosen_dishes } %>
        </div>
        <%= f.hidden_field :list_of_dishes, id: 'list_of_dishes' %>
        
        <% end %>
        
      </div>
      <div class='col-md-6'>
        <div class="chosen-dishes">
          <div class='section-header'>
            <span class='section-header__title h2'>Available Dishes</span>
          </div>
          <div class="available_dishes">
            <%= render partial: 'available_dishes', locals: { available_dishes: @available_dishes } %>
          </div>
          <%= link_to 'Add to Meal Plan', '#', class: 'btn add-meal-plan pull-right', id: "add_dishes_btn" %>
          <%#= link_to 'Add Custom Dish', custom_dish_path, :remote => true, class: 'btn pull-right add-custom-dish' %>
          <%= link_to 'Add Custom Dish', dishes_new_path, class:'btn pull-right' %>
        </div>
    </div>
  </div>
</div> <!-- container -->

<script>
  var calories = 0;
  var fats = 0;
  var carbs = 0;
  var list_of_dishes = [];
  
  function refresh_dish_list() {
    $.ajax({
      url: '/meal_plans/new/refresh_dish_list',
      type: 'POST',
      dataType: 'script',
      data: {
        location: $('#location_id').val(),
        course: $('#course_id').val()
      }
    });
  }

  $(document).ready(function() {

    window.odometerOptions = {
      auto: false,
      format: '(,ddd)',
      duration: 500,
      theme: 'minimal',
      animation: 'count'
    }



    $(document).on('click', 'tr.table_row', function() {
      console.log("Hit")
      // On click, add ID to array, save into global variable. Add Button at bottom of available dishes to submit
      if (list_of_dishes.indexOf($(this).children(".dish_name").attr("id")) === -1 ) {
        list_of_dishes.push($(this).children(".dish_name").attr('id'));
      }
      $(this).addClass('success');
    });

    $('#add_dishes_btn').on('click', function() {
      $.ajax({
        url: '/meal_plans/new/update_dish_list',
        type: 'GET',
        dataType: 'script',
        data: {
          data_value: list_of_dishes
        }
      });
      $('#list_of_dishes').val(list_of_dishes);
      event.preventDefault();
      $('tr.table_row').removeClass('success');

    });

    $("#location_id").on('change', refresh_dish_list);
    $("#course_id").on('change', refresh_dish_list);

  });


</script>

app/views/users/show.html.erb
<div class="container">
  <div class="jumbotron text-center">
    <h2><%= @user.first_name %> <%= @user.last_name %></h2><br>
        <p><%= @user.email_address %></p>
  </div>
  <div class="panel panel-default">
    <div class="panel-body">
        <h3 style="text-align:left;">Meal Plans</h3>
        <table class="table table-hover table-bordered">
          <tr>
            <th scope="col">Name</th>
            <th scope="col">Course</th>
            <th scope="col">Date</th>
            <th scope="col">Actions</th>
          </tr>
          <% @meal_plans.each do |plan| %>
            <tr>
              <td scope="row"><%= plan.name %></td>
              <td>Lunch</td>
              <td><%= plan.date.strftime("%m/%d/%Y") %></td>
              <td><%= link_to "Show", meal_plan_path(plan) %> <%= link_to "Delete", controller: 'meal_plans', action: 'destroy', id: plan.id, method: :delete %></td>
            </tr>
          <% end %>
        </table>
        <%= link_to "New Meal Plan", new_meal_plan_path, class: 'btn btn-primary pull-right' %>
    </div>
  </div>
</div>