config/routes.rb
Rails.application.routes.draw do
  get 'dishes/create'
  get 'dishes/new'
  get 'welcome/index'
  root 'welcome#index'
  get 'meal_plans/new'
  post 'meal_plans/create'
  get 'meal_plans/edit'
  get 'sessions/new'
  root 'static_pages#home'
  get 'meal_plans/new/update_dish_list', to: 'meal_plans#update_dish_list', as: 'update_dish_list'
  get 'meal_plans/new/custom_dish', to: 'meal_plans#custom_dish', as: 'custom_dish' 
  post 'meal_plans/new/refresh_dish_list', to: 'meal_plans#refresh_dish_list', as: 'refresh_dish_list'
  get '/home', to: 'static_pages#home'
  get '/about', to: 'static_pages#about'
  get '/signup', to: 'users#new', as: 'new_user'
  post '/signup', to: 'users#create'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :users
  resources :meal_plans
  resources :dishes

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dish.rb
class Dish < ApplicationRecord

  has_many :meal_plans

end

app/models/meal_plan.rb
class MealPlan < ApplicationRecord
  belongs_to :user
  has_one :restriction
  has_many :dishes

  validates :name, presence: true
  validates :date, presence: true

  serialize :list_of_dishes

  accepts_nested_attributes_for :dishes

end

app/models/restriction.rb
class Restriction < ApplicationRecord
  belongs_to :meal_plan
end

app/models/user.rb
class User < ApplicationRecord
  validates :username, presence: true, 
                       length: { maximum: 50 }, 
                       uniqueness: true

  has_many :meal_plans
  serialize :meal_plans
end

app/models/weekly_menu.rb
class WeeklyMenu < ApplicationRecord
  has_many :dishes
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def new
  end
end

app/controllers/dishes_controller.rb
class DishesController < ApplicationController
  def create
  	@dish = Dish.new(dish_params)
    if @dish.save
      #log_in(@user)
      flash[:success] = "Welcome to Custom Meal Maker"
      redirect_to meal_plans_new_path
    else
      flash.now[:danger] = "Error creating account"
      #render 'new'
    end
  end

  def new
  	@dish = Dish.new
    #@available_dishes = nil # will be by weekly once week is implemented
    #@chosen_dishes = nil
  end

private

	def dish_params
      params.require(:dish).permit(:created_at, :updated_at, :name, :calories, :total_fat, :cholesterol, :sodium, :carbs, :suger, :protein, :location, :course)
    end

end


=begin

<%= f.hidden_field :user_id, :value => current_user.id %>

    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.string "name"
    t.integer "calories"
    t.integer "total_fat"
    t.integer "cholesterol"
    t.integer "sodium"
    t.integer "carbs"
    t.integer "suger"
    t.integer "protein"
    t.string "location"
    t.string "course"

=end

app/controllers/test_controller.rb
class TestController < ApplicationController
  def thing
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include SessionsHelper
  
  def create
    @user = User.new(user_params)
    if @user.save
      log_in(@user)
      flash[:success] = "Welcome to Manoa Meals"
      redirect_to user_path(@user)
    else
      flash.now[:danger] = "Error creating account"
      render 'new'
    end
  end

  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
    @meal_plans = MealPlan.where(user_id: @user.id)
    
  end

  private

    def user_params
      params.require(:user).permit(:username, :email_address, :first_name, :last_name)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/dishes_helper.rb
module DishesHelper
end

app/helpers/meal_plans_helper.rb
module MealPlansHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    if session[:user_id]
      @current_user ||= User.find_by(id: session[:user_id])
    end
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/test_helper.rb
module TestHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">

  <link href="https://fonts.googleapis.com/css?family=Raleway" rel="stylesheet">

  <small style="font-family:Raleway">
    Manoa Meals 
    by <a href="https://github.com/solliegarcia">Sollie</a>,
    <a href="https://github.com/Liloa">Umi</a>,
    <a href="https://github.com/garyjw">Gary</a>,
    <a href="https://github.com/kjp236">Kevin</a>

  </small>
  <nav style="font-family:Raleway">
    <ul>
      <li>University of Hawaii at Manoa</li>
      <li>ICS 414</li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">

    <link href="https://fonts.googleapis.com/css?family=Fredericka+the+Great|Raleway" rel="stylesheet">

    

    <%= link_to "Manoa Meals", home_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
          <li><%= link_to "Create A Plan", meal_plans_new_path %></li>
        <% end %>
        <li><%= link_to "About", about_path %></li>
        <% if logged_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", '#' %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>

      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Vagrant</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'odometer.min.js', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="http://github.hubspot.com/odometer/themes/odometer-theme-minimal.css" />
    <script src="http://github.hubspot.com/odometer/odometer.js"></script>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>